name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable

    - uses: shuttle-hq/deploy-action@v2
      name: ShuttleHQ deploy
      with:
        shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
        project-id: proj_01J9VAC6QE1YKZXRHWPXR7NWJH
        secrets: |
          DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
