name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ShuttleHQ deploy
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
