name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install latest Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: shuttle-hq/deploy-action@main
      name: ShuttleHQ deploy
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
        secrets: |
          DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
